name: Size Limit

on:
  pull_request:
    branches:
      - main

jobs:
  size-limit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup Node.js 20
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 20
          cache: yarn
        env:
          # https://github.com/actions/setup-node/issues/531#issuecomment-1819151412
          SKIP_YARN_COREPACK_CHECK: 1

      - name: Enable Corepack
        run: corepack enable

      - name: Install Dependencies
        run: yarn --immutable

      - uses: andresz1/size-limit-action@e7493a72a44b113341c0cf6186ab49c17c4b65c1 # v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_step: install
          script: yarn size-limit --json
